# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Web_HostAddress = https://localhost:5001

@Email=administrator@localhost
@Password=Administrator1!
@BearerToken=CfDJ8KDP98tlKjNGkk48ugmxKJTjRemMaJZRn08PdT_HXQ_5ng9lSKoEqSUC7riQanSntb_PSGcF1sTz3jqsbF8BX__owxaRCPT52R_zkqaUBvsaXbziLnX4b8Vwrp91bdO8vAWb_-Is5dbTWSR7l6D1tBpvXDCa8IsZEG9TXnSwOEF3k3ng4Pv3utzn7xl0mEAqFsmUR1yBtyKn9V4KTWjNbHFxOkuF5UKx6z_R6DXyzjk7uM9ccIezQVWq1NX0CbSkkT0wDHDZ9o8EHMTAGt38LFc_JThvKXTY4EhRy0e1ZXmbqdrRQtP_7TuZtFD3fhQQwdXdD5jA7jlieY2YOJqz4VAeijrhNcPkQD1RznrpCWXAbNkVVApmxOCkAmYMp8y7tSrZVzBxhPUXWDdPE6akP0qubWA8tYsDUr0SkXY3rQd2DgZhG8mo5iH1SvwyHTswhnRhSNUurgYHDupycbqZhB_shjLp5SrwLA11hbgQT_59F0YR2ObQGWI06ULaqd0H2C56kZwTopzP1Zc8WpmfSvOyxTcdvKujl4wf0A-JJOXI-dkTxodWjOW0ZFFvC2-DlVbk57lCvVdgGN6xQ7TQDrJrcS92sr4gQlOXtAs7rxnroXBMwwaciwnqzEfvqKwnISpZquWaKPCqgz9lfZr31Qr-YgpQ3NoLrZu7K7FStWZUtn8APpmVOFX4xIF6F6vCC7wMBTJLJ_ZBvJhsSp_wQYdIZedYoonPMFYi7kw97qb1JlutJB0I55O44-o-IgSuZ10wxPKWdeuHmK3kVciaFOTuEB1OrCCPcFwnm-MNgECKXdnIoOiRktL3apPfRlwJYA

# POST Users Register
POST {{Web_HostAddress}}/api/Users/Register
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Login
POST {{Web_HostAddress}}/api/Users/Login
Content-Type: application/json

{
  "email": "{{Email}}",
  "password": "{{Password}}"
}

###

# POST Users Refresh
POST {{Web_HostAddress}}/api/Users/Refresh
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

{
  "refreshToken": ""
}

###

# POST MovieRates
POST {{Web_HostAddress}}/api/MovieRates
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateMovieRatesCommand
{
  "MovieId": 0,
  "Rate": 0
}

###

# GET WeatherForecast
GET {{Web_HostAddress}}/api/WeatherForecasts
Authorization: Bearer {{BearerToken}}

###

# GET TodoLists
GET {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}

###

# POST TodoLists
POST {{Web_HostAddress}}/api/TodoLists
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// CreateTodoListCommand
{
  "Title": "Backlog"
}

###

# PUT TodoLists
PUT {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoListCommand
{
  "Id": 1,
  "Title": "Product Backlog"
}

###

# DELETE TodoLists
DELETE {{Web_HostAddress}}/api/TodoLists/1
Authorization: Bearer {{BearerToken}}

###

# GET TodoItems
@PageNumber = 1
@PageSize = 10
GET {{Web_HostAddress}}/api/TodoItems?ListId=1&PageNumber={{PageNumber}}&PageSize={{PageSize}}

Authorization: Bearer {{BearerToken}}

###



#PUT TodoItems UpdateItemDetails
PUT {{Web_HostAddress}}/api/TodoItems/UpdateItemDetails?Id=1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemDetailCommand
{
  "Id": 1,
  "ListId": 1,
  "Priority": 3,
  "Note": "This is a good idea!"
}

###

# PUT TodoItems
PUT {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}
Content-Type: application/json

// UpdateTodoItemCommand
{
  "Id": 1,
  "Title": "Eat a yummy burrito 🌯",
  "Done": true
}

###

# DELETE TodoItem
DELETE {{Web_HostAddress}}/api/TodoItems/1
Authorization: Bearer {{BearerToken}}

###